const MessageUtils = {
  SUCCESS: {
    USER_REGISTERED: "User registered successfully",
    LOGIN_SUCCESS: "Login successful",
    POST_SUCESS: "Post created sucessfully",
    POST_UPDATED: "Post updated sucessfully",
    DELETE_UPDATED: "Post deleted sucessfully",
    COMMENT_DELETED: "Comment deleted sucessfully",
    OK: "OK",
    Post_FETCHED: "All Posts Fetched",
    Post_Fetch: "Post Fetched",
    COMMENT_SUCESS: "Comment created Sucessfully",
    COMMENT_FETCH: "Comment fetch",
    COMMENT_UPDATED: "Comment Updated",
    LIKE_SUCESS: "Like Created Sucessfully",
    LIKE_REMOVED: "Like Removed",
    LIKE_FETCHED: "Likes Fetched",
    DATABASE_CONNECTION_SUCESSFUL:
      "Database connection established sucessfully",
  },

  ERROR: {
    REGISTRATION_FAILED: "Registration failed",
    LOGIN_FAILED: "Login failed",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    USER_NOT_FOUND: "User not found",
    ERROR_ADDING_POST: "Error in adding post",
    POST_ADD_FAIL: "Error in adding Post",
    POST_NOT_FOUND: "Post Not Found",
    POST_NOT_UPDATED: "Post not updated",
    POST_DELETION_FAILED: "Post deletion failed",
    POST_FETCH_FAILED: "Post fetch failed",
    ERROR_ADDING_COMMENT: "Error adding comment",
    PARENT_COMMENT_NOT_FOUND: "Parent comment not found",
    COMMENT_FETCH_FAILED: "Comment Fetch failed",
    COMMENT_DELETION_FAILED: "Comment deletion failed",
    COMMENT_NOT_FOUND: "comment Not found",
    COMMENT_UPDATION_FAILED: "comment updation filed",
    LIKE_NOT_FOUND: "Like not found",
    LIKE_NOT_REMOVED: "Like not removed",
    EMAIL_ALREADY_EXIST: "Email already exist",
    POST_ID_IS_REQUIRED: "post_id is required when likeType is Post",
    COMMENT_ID_IS_REQUIRED: "Comment_id is required when likeType is comment",
    ALREADY_LIKED: "Already liked",
    ERROR_FINDING_LIKE: "Error finding like",
    FETCHING_PROBLEM_ERROR: "Error fetching likes",
    UNABLE_TO_CONNECT_DATABASE: "Unable to connect to databse",
  },
};

export default MessageUtils;
